chore: migrate to owlboyt
googleapis/java-containeranalysis pull request #696
Opened 2021-09-10 18:26 UTC by Neenu1995

2021-09-14 17:23 UTC, eaball35 approved these changes

2021-09-17 22:11 UTC, kelsk approved these changes

2021-09-23 16:07 UTC, chingor13 requested changes

2021-09-23 16:07 UTC, chingor13 commented on .github/.OwlBot.yaml
> +- "/google-cloud-containeranalysis/src/main/java/com/google/cloud/devtools/containeranalysis/v1/GrafeasUtils.java"
These are regexes, so we can simplify these lists

2021-12-02 23:31 UTC, eaball35 approved these changes

2021-12-03 19:23 UTC, closed without merging